### ISSUE TITLE
README and CHANGELOG not updating

### ISSUE THREAD

**Issue by hkellaway** [CocoaPods/cocoapods.org#201]
i've noticed the README and CHANGELOG updating inconsistently for my most recently updated pod - http://cocoapods.org/pods/Gloss . for example, the CHANGELOG on Github reflects changes for the latest version, 0.5.1 - these are not reflected on the CocoaPods page :confused:

**Comment by dcirne** [comment]
The same is happening to my pods as well. Changes are displayed correctly on GitHub (https://github.com/mParticle/mParticlePod), but incorrectly at CocoaPods (https://cocoapods.org/pods/mParticle). It should be showing version 4.4.0, instead it is showing data from version 4.3.0

**Comment by orta** [comment]
Looks like CocoaDocs was down for a day or so, I've asked set it back up and asked it to run the last 3 days worth of pods. Should fix the most recent issues.

**Comment by dcirne** [comment]
Did the service come back up? It seems the issue is still there.

**Comment by orta** [comment]
Hrm, interesting, it did, and it should have fixed this

**Comment by marcbaldwin** [comment]
It fixed the issue for my pod https://cocoapods.org/pods/GestureRecognizerClosures

**Comment by floere** [comment]
@hkellaway @dcirne What's the status on this issue?

**Comment by dcirne** [comment]
It has been working for me. This issue can be closed.

**Comment by floere** [comment]
@dcirne Thank you for the quick feedback! :rocket:

**Comment by gwennguihal** [comment]
I have the same issue, two years after on my pod: https://cocoapods.org/pods/Collor

**Comment by kringelbach** [comment]
An additional two years have passed and my Changelog is still not being updated when I publish a new version of my pod. I cannot find any information on how to include the Changelog, but it shows the Changelog for version 4.6.2 even though I have published several versions since then with the Changelog in the exact same location.
Am I doing something wrong?
