### ISSUE TITLE
README and CHANGELOG not updated

### ISSUE THREAD

**Issue by n3trino** [CocoaPods/cocoapods.org#324]
# Report

## What did you do?

pod trunk push WOVER.podspec

## What did you expect to happen?

Update README.md and CHANGELOG.md included inside zip file to latest version of pod.

## What happened instead?

Keeps README.md and CHANGELOG.md from previous version.

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/stavrosschizas/.rvm/rubies/ruby-2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 01275f74bd2fed6db034f7a40d84635a0a960b7f
```

### Installation Source

```
Executable Path: /Users/stavrosschizas/.rvm/gems/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://cocoapods.org/pods/WOVER

**Comment by vadimstarikov** [comment]
We have the same issue with https://cocoapods.org/pods/TrivverSDK and https://github.com/Saritasa/Trivver-IOS-SDK

**Comment by orta** [comment]
This should probably be fixed by https://github.com/CocoaPods/trunk.cocoapods.org/pull/235 and https://github.com/CocoaPods/cocoadocs.org/pull/555 - you're welcome to run through the help instructions [in the README](https://github.com/CocoaPods/cocoapods.org#getting-help)

**Comment by raspu** [comment]
I am having this issue also (https://cocoapods.org/pods/Highlightr). I tried with the instruction on the [README file](https://github.com/CocoaPods/cocoapods.org#getting-help), but it's pointing to an ip address that doesn't seem to be up anymore.

**Comment by sisoje** [comment]
this is still an issue.
in my old pod i removed all files and did a clean pod lib create (with same pod name as before)
after pushing completely new files still no readme update.
something seems to be stucked :(

**Comment by raspu** [comment]
Hey @orta, it's possible to re-open this issue? Or shall we create a new one?

**Comment by sisoje** [comment]
more info can be seen using this url:
https://cocoadocs.buddybuild.com/error/PromiseKit
https://cocoadocs.buddybuild.com/error/Alamofire
...

seems like every pod is affected, and yet ticket is closed?

**Comment by ganeshfaterpekar** [comment]
Hey @orta, we are stilling facing the issue. Pod is getting updated, however, the readme does not update.

https://cocoapods.org/pods/paper-onboarding-pointzi
https://gitlab.com/pointzi/sdks/paper-onboarding-ios

**Comment by pedro-otoai** [comment]
Facing the same issue here as well. Any solutions?

**Comment by mbijapur** [comment]
Facing the same issue. Has anyone found any solution yet?
